name: F2D User Authentication

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # checkout code
      - name: Checkout User Authentication Repo
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build And Test
        run: | 
          mvn clean install
          mvn test

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: | 
          docker build -t ${{ secrets.DOCKER_USERNAME }}/f2d-user-authentication:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/f2d-user-authentication:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker stop f2d-user-authentication || true
            docker rm f2d-user-authentication || true
            docker pull ${{ secrets.DOCKER_USERNAME}}/f2d-user-authentication:latest
            docker run -d --name f2d-user-authentication -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/f2d-user-authentication:latest
        
    

