name: Run Maven on Raspberry Pi

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # SSH into Raspberry Pi to run Maven commands
      - name: Run Maven Commands on Raspberry Pi
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RASPBERRY_PI_IP }}
          username: ${{ secrets.RASPBERRY_PI_USER }}
          password: ${{ secrets.RASPBERRY_PI_PASSWORD }}
          port: 22
          script: |
            echo "Navigating to project directory on Raspberry Pi"
            cd /home/ej/F2D/f2d-user-authentication

            echo "Cleaning project"
            mvn clean
