name: Run Maven on Raspberry Pi

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted  # Use the self-hosted runner on Raspberry Pi

    steps:
      # Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Run Maven commands
      - name: Run Maven Commands
        run: |
          echo "Navigating to project directory"
          cd /home/ej/F2D/f2d-user-authentication

          echo "Cleaning project"
          mvn clean