name: Run Maven on Raspberry Pi

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted  # Use the self-hosted runner on Raspberry Pi

    steps:
      # Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Run Maven commands
      - name: Run Maven Commands
        uses: appleboy/ssh-action@master
        with:
          host: 192.168.1.54
          username: ej
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            echo "Navigating to project directory"
            cd /home/ej/F2D/f2d-user-authentication

            echo "Cleaning project"
            mvn clean

            echo "Building project"
            mvn package -Dspring.datasource.url=${{ secrets.DB_HOST }} -Dspring.datasource.username=${{ secrets.DB_USERNAME }} -Dspring.datasource.password=${{ secrets.DB_PASSWORD }}
